#!/bin/bash

if [ -z "$PS1" ] ; then
    echo -e "This script must be sourced. Use \"source ${BASH_SOURCE[0]}\" instead."
    exit
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
FLAG=$DIR/maben_set

VDATE_TIMESTAMP="$( cd ${DIR} && git log -1 --format=%at -1)"
VDATE_TIMESTAMP_PREVIOUS="$(($VDATE_TIMESTAMP - 86400))"
VDATE="$( date --date @$VDATE_TIMESTAMP_PREVIOUS +'%Y-%m-%d')"
VERSION="$( date --date @$VDATE_TIMESTAMP +'%y%m%d')"
VERSION_COUNT="$( cd ${DIR} && git rev-list --count --since=$VDATE HEAD)"

if [ ! -f $FLAG ]; then
	echo "source $DIR/init" >> ~/.bashrc
    touch $FLAG
fi

if [ -z ${MABEN+x} ]; then
	export MABEN="maben v$VERSION.$VERSION_COUNT initializated at `date` to $DIR"
	export MABEN_PATH=$DIR
	export PATH=$PATH:$DIR/bin
else
	echo "maben already initializated";
fi

maben --check
