#!/bin/bash

if [ -z "$PS1" ] ; then
    echo -e "This script must be sourced. Use \"source ${BASH_SOURCE[0]}\" instead."
    exit
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
FLAG=$DIR/maben_set

VDATE_TIMESTAMP="$( cd ${DIR} && git log -1 --format=%at -1)"
VDATE_TIMESTAMP_PREVIOUS="$(($VDATE_TIMESTAMP - 86400))"
VDATE="$( date --date @$VDATE_TIMESTAMP_PREVIOUS +'%Y-%m-%d')"
VERSION="$( date --date @$VDATE_TIMESTAMP +'%y%m%d')"
VERSION_COUNT="$( cd ${DIR} && git rev-list --count --since=$VDATE HEAD)"

if [ ! -f $FLAG ]; then
	$DIR/bin/dependencies
	if [ $? -eq 0 ]; then
		echo "source $DIR/init" >> ~/.bashrc
		touch $FLAG
	else
		echo "$(tput setaf 1)Not installed $(tput sgr0)"
	fi
fi

if [ -f $FLAG ]; then
	if [ -z ${MABEN+x} ]; then
		echo "v$VERSION.$VERSION_COUNT" > $DIR/maben_version
		echo "`date`" > $DIR/maben_init_date
		export MABEN="maben v$VERSION.$VERSION_COUNT"
		export MABEN_PATH=$DIR
		export PATH=$PATH:$DIR/bin
	else
		echo "maben already initializated";
	fi
	maben --autocheck
fi
